[package]
name = "temp-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
